version: '3'
volumes:
  data:
networks:
  apinet:
services:
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: donotuse
      MYSQL_DATABASE: bdtestsqlalchemy
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - data:/var/lib/mysql
    networks:
      - apinet
    ports:
      - "3306:3306"
  api:
    build: .
    container_name: api-rest-flask-jose
    restart: always
    depends_on: 
      - db
    networks:
      - apinet
    ports:
      - "5000:5000"
      - "80:80"
      